### ISSUE TITLE
Use Strict?

### ISSUE THREAD

**Issue by ranneyd** [hownowbrowncow/material-timepicker#13]
Should you have 'use strict' in timepicker.js? Is it not necessary?

**Comment by hownowbrowncow** [comment]
ES6 modules are always in strict mode so there is no need to add it manually http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code. Also babel add the `use strict;` statement when compiling https://github.com/hownowbrowncow/material-timepicker/blob/master/dist/js/timepicker.js#L1.
